services:
  - type: web
    name: mold-prediction-tool
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: "mold_kit_secret_key_2024"
      - key: OPENWEATHER_API_KEY
        value: "d6159ecc80513ec0218d61d4285e2d52"
      - key: ADMIN_PASSWORD
        value: "moldadminpass"
      - key: UPLOAD_FOLDER
        value: "uploads"